codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  ignore:
    - "MCCommonTableView"
    - "Classes/*.m"
    - "Classes/MCCommonTableViewCell.*"
  precision: 2
  round: down
  range: "0...100"

  status:
    project: yes
    patch: yes
    changes: no

  parsers:
     gcov:
       branch_detection:
         conditional: yes
         loop: yes
         method: no
         macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
